version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ./PokeAppMVC/PokeAppMVC/PokeAppMVC.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output PokeAppMVC/PokeAppMVC/PokeAppMVC.csproj
artifacts:
  files:
    - appspec.yml
    - PokeAppMVC.exe
    - scripts/*
