// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using PokeAppMVC;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace PokeAppMVC
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Welcome
    {
        [JsonProperty("cards", NullValueHandling = NullValueHandling.Ignore)]
        public List<Card> Cards { get; set; }
    }

    public partial class Card
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("nationalPokedexNumber", NullValueHandling = NullValueHandling.Ignore)]
        public long? NationalPokedexNumber { get; set; }

        [JsonProperty("imageUrl")]
        public Uri ImageUrl { get; set; }

        [JsonProperty("imageUrlHiRes")]
        public Uri ImageUrlHiRes { get; set; }

        [JsonProperty("types", NullValueHandling = NullValueHandling.Ignore)]
        public List<RetreatCost> Types { get; set; }

        [JsonProperty("supertype")]
        public Supertype Supertype { get; set; }

        [JsonProperty("subtype")]
        public string Subtype { get; set; }

        [JsonProperty("evolvesFrom", NullValueHandling = NullValueHandling.Ignore)]
        public EvolvesFrom? EvolvesFrom { get; set; }

        [JsonProperty("ability", NullValueHandling = NullValueHandling.Ignore)]
        public Ability Ability { get; set; }

        [JsonProperty("hp", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? Hp { get; set; }

        [JsonProperty("convertedRetreatCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? ConvertedRetreatCost { get; set; }

        [JsonProperty("number")]
        public string Number { get; set; }

        [JsonProperty("artist", NullValueHandling = NullValueHandling.Ignore)]
        public string Artist { get; set; }

        [JsonProperty("rarity")]
        public Rarity Rarity { get; set; }

        [JsonProperty("series")]
        public string Series { get; set; }

        [JsonProperty("set")]
        public string Set { get; set; }

        [JsonProperty("setCode")]
        public string SetCode { get; set; }

        [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Text { get; set; }

        [JsonProperty("attacks", NullValueHandling = NullValueHandling.Ignore)]
        public List<Attack> Attacks { get; set; }

        [JsonProperty("weaknesses", NullValueHandling = NullValueHandling.Ignore)]
        public List<Resistance> Weaknesses { get; set; }

        [JsonProperty("resistances", NullValueHandling = NullValueHandling.Ignore)]
        public List<Resistance> Resistances { get; set; }

        [JsonProperty("retreatCost", NullValueHandling = NullValueHandling.Ignore)]
        public List<RetreatCost> RetreatCost { get; set; }
    }

    public partial class Ability
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Attack
    {
        [JsonProperty("cost")]
        public List<RetreatCost> Cost { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("damage")]
        public string Damage { get; set; }

        [JsonProperty("convertedEnergyCost")]
        public long ConvertedEnergyCost { get; set; }
    }

    public partial class Resistance
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("value")]
        public ValueUnion Value { get; set; }
    }

    public enum RetreatCost { Colorless, Grass, Metal };

    public enum EvolvesFrom { BeedrillEx, Kakuna };

    public enum Rarity { Common, Rare, RareHolo };

    public enum TypeEnum { Fighting, Fire };

    public enum ValueEnum { The2, The30 };

    public enum Supertype { Pokémon, Trainer };

    public partial struct ValueUnion
    {
        public ValueEnum? Enum;
        public long? Integer;

        public static implicit operator ValueUnion(ValueEnum Enum) => new ValueUnion { Enum = Enum };
        public static implicit operator ValueUnion(long Integer) => new ValueUnion { Integer = Integer };
    }

    public partial class Welcome
    {
        public static Welcome FromJson(string json) => JsonConvert.DeserializeObject<Welcome>(json, PokeAppMVC.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Welcome self) => JsonConvert.SerializeObject(self, PokeAppMVC.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                RetreatCostConverter.Singleton,
                EvolvesFromConverter.Singleton,
                RarityConverter.Singleton,
                TypeEnumConverter.Singleton,
                ValueUnionConverter.Singleton,
                ValueEnumConverter.Singleton,
                SupertypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class RetreatCostConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(RetreatCost) || t == typeof(RetreatCost?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Colorless":
                    return RetreatCost.Colorless;
                case "Grass":
                    return RetreatCost.Grass;
                case "Metal":
                    return RetreatCost.Metal;
            }
            throw new Exception("Cannot unmarshal type RetreatCost");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (RetreatCost)untypedValue;
            switch (value)
            {
                case RetreatCost.Colorless:
                    serializer.Serialize(writer, "Colorless");
                    return;
                case RetreatCost.Grass:
                    serializer.Serialize(writer, "Grass");
                    return;
                case RetreatCost.Metal:
                    serializer.Serialize(writer, "Metal");
                    return;
            }
            throw new Exception("Cannot marshal type RetreatCost");
        }

        public static readonly RetreatCostConverter Singleton = new RetreatCostConverter();
    }

    internal class EvolvesFromConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(EvolvesFrom) || t == typeof(EvolvesFrom?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Beedrill-EX":
                    return EvolvesFrom.BeedrillEx;
                case "Kakuna":
                    return EvolvesFrom.Kakuna;
            }
            throw new Exception("Cannot unmarshal type EvolvesFrom");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (EvolvesFrom)untypedValue;
            switch (value)
            {
                case EvolvesFrom.BeedrillEx:
                    serializer.Serialize(writer, "Beedrill-EX");
                    return;
                case EvolvesFrom.Kakuna:
                    serializer.Serialize(writer, "Kakuna");
                    return;
            }
            throw new Exception("Cannot marshal type EvolvesFrom");
        }

        public static readonly EvolvesFromConverter Singleton = new EvolvesFromConverter();
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }

    internal class RarityConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Rarity) || t == typeof(Rarity?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Common":
                    return Rarity.Common;
                case "Rare":
                    return Rarity.Rare;
                case "Rare Holo":
                    return Rarity.RareHolo;
            }
            throw new Exception("Cannot unmarshal type Rarity");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Rarity)untypedValue;
            switch (value)
            {
                case Rarity.Common:
                    serializer.Serialize(writer, "Common");
                    return;
                case Rarity.Rare:
                    serializer.Serialize(writer, "Rare");
                    return;
                case Rarity.RareHolo:
                    serializer.Serialize(writer, "Rare Holo");
                    return;
            }
            throw new Exception("Cannot marshal type Rarity");
        }

        public static readonly RarityConverter Singleton = new RarityConverter();
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Fighting":
                    return TypeEnum.Fighting;
                case "Fire":
                    return TypeEnum.Fire;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            switch (value)
            {
                case TypeEnum.Fighting:
                    serializer.Serialize(writer, "Fighting");
                    return;
                case TypeEnum.Fire:
                    serializer.Serialize(writer, "Fire");
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }

    internal class ValueUnionConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ValueUnion) || t == typeof(ValueUnion?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    switch (stringValue)
                    {
                        case "+30":
                            return new ValueUnion { Enum = ValueEnum.The30 };
                        case "×2":
                            return new ValueUnion { Enum = ValueEnum.The2 };
                    }
                    long l;
                    if (Int64.TryParse(stringValue, out l))
                    {
                        return new ValueUnion { Integer = l };
                    }
                    break;
            }
            throw new Exception("Cannot unmarshal type ValueUnion");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (ValueUnion)untypedValue;
            if (value.Enum != null)
            {
                switch (value.Enum)
                {
                    case ValueEnum.The30:
                        serializer.Serialize(writer, "+30");
                        return;
                    case ValueEnum.The2:
                        serializer.Serialize(writer, "×2");
                        return;
                }
            }
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value.ToString());
                return;
            }
            throw new Exception("Cannot marshal type ValueUnion");
        }

        public static readonly ValueUnionConverter Singleton = new ValueUnionConverter();
    }

    internal class ValueEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ValueEnum) || t == typeof(ValueEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "+30":
                    return ValueEnum.The30;
                case "×2":
                    return ValueEnum.The2;
            }
            throw new Exception("Cannot unmarshal type ValueEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (ValueEnum)untypedValue;
            switch (value)
            {
                case ValueEnum.The30:
                    serializer.Serialize(writer, "+30");
                    return;
                case ValueEnum.The2:
                    serializer.Serialize(writer, "×2");
                    return;
            }
            throw new Exception("Cannot marshal type ValueEnum");
        }

        public static readonly ValueEnumConverter Singleton = new ValueEnumConverter();
    }

    internal class SupertypeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Supertype) || t == typeof(Supertype?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Pokémon":
                    return Supertype.Pokémon;
                case "Trainer":
                    return Supertype.Trainer;
            }
            throw new Exception("Cannot unmarshal type Supertype");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Supertype)untypedValue;
            switch (value)
            {
                case Supertype.Pokémon:
                    serializer.Serialize(writer, "Pokémon");
                    return;
                case Supertype.Trainer:
                    serializer.Serialize(writer, "Trainer");
                    return;
            }
            throw new Exception("Cannot marshal type Supertype");
        }

        public static readonly SupertypeConverter Singleton = new SupertypeConverter();
    }
}
